name: Gradle Build

on:
  push:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set Java 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: corretto
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: |
          ./gradlew setupDecompWorkspace
          ./gradlew build
      - name: List files
        run: ls
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: 3arthh4ck
          path: ./build/libs/*release.jar  
